name:  'Repos bugbash issue'
title: 'Bug title'
description: 'Issue found during a team bug bash.'
labels: ['bugbash', 'bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  Please include/attach any additional data like urls and screenshots that will help explain the issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: url
    attributes:
      label: Url
      description: What is the url where you see the issue?
      placeholder: url here please
      value: "github.com"
  - type: textarea
    id: repro
    attributes:
      label: repro-steps
      description: What are the steps to reproduce this issue?
      placeholder: |
        1. 
        2.
        3.
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: feature-area
    attributes:
      label: What feature area?
      multiple: true
      options:
        - Search
        - Tree
        - Blob
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log/console output
      description: Please copy and paste any relevant log output or erros. This will be automatically formatted into code, so no need for backticks.
      render: shell
